"""Combine per-signal scores into a single attribution + label.

Design decisions (documented in README):

  * The LLM signal is weighted higher (0.65 vs 0.35) because it captures
    semantic coherence — patterns of hedging, generic transitions, etc. —
    that pure statistics miss. The stylometric signal is kept in the mix
    as an independent structural check that catches uniform prose the LLM
    might read as "polished writing".

  * Thresholds are asymmetric on purpose: the "uncertain" band is wide
    (0.30 < score < 0.75) so the system defaults to "we don't know" rather
    than confidently mislabelling a human writer as AI. That's the false-
    positive asymmetry the assignment's hints call out.

  * When a signal degrades (LLM API down, text too short for stylometry),
    the pipeline pulls the combined score back toward 0.5 — half-blind
    detectors don't get to be highly confident.
"""

from __future__ import annotations

from typing import Any

# Weighting when both signals are healthy.
LLM_WEIGHT = 0.65
STYLOMETRIC_WEIGHT = 0.35

# Attribution thresholds on the combined AI-probability.
AI_THRESHOLD = 0.75
HUMAN_THRESHOLD = 0.30


def _combine(llm_result: dict[str, Any], style_result: dict[str, Any]) -> float:
    """Return the combined AI-probability in [0, 1].

    Degradation policy: if a signal is not ok, its evidence pulls toward
    0.5 rather than being trusted at face value. If both are down we
    return the neutral 0.5.
    """
    llm_ok = llm_result.get("ok", False)
    style_ok = style_result.get("ok", False)
    llm_score = float(llm_result.get("score", 0.5))
    style_score = float(style_result.get("score", 0.5))

    if llm_ok and style_ok:
        return LLM_WEIGHT * llm_score + STYLOMETRIC_WEIGHT * style_score
    if llm_ok and not style_ok:
        return 0.7 * llm_score + 0.3 * 0.5
    if style_ok and not llm_ok:
        return 0.5 * style_score + 0.5 * 0.5
    return 0.5


def _classify(ai_probability: float) -> tuple[str, float]:
    """Map an AI-probability to (attribution, confidence).

    `confidence` is the strength of the specific verdict:
      * "likely_ai": ai_probability itself
      * "likely_human": 1 - ai_probability
      * "uncertain": how strongly we're near the mid-band (1 at 0.5, 0 at
        either threshold), so the label copy can say "reflects genuine
        uncertainty" honestly.
    """
    if ai_probability >= AI_THRESHOLD:
        return "likely_ai", ai_probability
    if ai_probability <= HUMAN_THRESHOLD:
        return "likely_human", 1.0 - ai_probability
    return "uncertain", 1.0 - 2.0 * abs(ai_probability - 0.5)


def _label_for(attribution: str, ai_probability: float) -> dict[str, str]:
    """Return the three-variant transparency label.

    Text is verbatim what the reader sees on the platform and what the
    README documents.
    """
    ai_pct = round(ai_probability * 100)
    human_pct = 100 - ai_pct

    if attribution == "likely_ai":
        return {
            "variant": "high_confidence_ai",
            "headline": "AI-generated (high confidence)",
            "body": (
                f"Our automated review estimates a {ai_pct}% likelihood that "
                "this content was generated by AI, based on a language-model "
                "assessment and stylometric analysis. The creator can appeal "
                "this classification if they believe it is incorrect."
            ),
        }
    if attribution == "likely_human":
        return {
            "variant": "high_confidence_human",
            "headline": "Human-written (high confidence)",
            "body": (
                f"Our automated review estimates a {human_pct}% likelihood "
                "that this content was written by a human, based on a "
                "language-model assessment and stylometric analysis. "
                "Automated attribution is imperfect — appeals are welcome."
            ),
        }
    return {
        "variant": "uncertain",
        "headline": "Attribution uncertain",
        "body": (
            "Our automated review could not confidently determine whether "
            "this content was written by a human or generated by AI "
            f"(AI-likelihood estimate: {ai_pct}%). This label reflects "
            "genuine uncertainty, not a verdict. Please read on your own "
            "judgment."
        ),
    }


def score_and_label(
    llm_result: dict[str, Any],
    style_result: dict[str, Any],
) -> dict[str, Any]:
    """Combine two signal outputs into the full attribution response.

    Returns a dict shaped for both the API response and the audit log:
      - attribution: "likely_ai" | "likely_human" | "uncertain"
      - ai_probability: 0-1
      - confidence: 0-1, strength of the specific verdict above
      - label: dict with variant, headline, body
      - signals: per-signal detail suitable for the audit log
    """
    ai_probability = _combine(llm_result, style_result)
    attribution, confidence = _classify(ai_probability)
    label = _label_for(attribution, ai_probability)

    return {
        "attribution": attribution,
        "ai_probability": round(ai_probability, 3),
        "confidence": round(confidence, 3),
        "label": label,
        "signals": {
            "llm": {
                "score": round(float(llm_result.get("score", 0.5)), 3),
                "ok": bool(llm_result.get("ok", False)),
                "model": llm_result.get("model"),
                "reasoning": llm_result.get("reasoning", ""),
            },
            "stylometric": {
                "score": round(float(style_result.get("score", 0.5)), 3),
                "ok": bool(style_result.get("ok", False)),
                "metrics": style_result.get("metrics", {}),
                "components": style_result.get("components", {}),
            },
        },
        "thresholds": {
            "ai": AI_THRESHOLD,
            "human": HUMAN_THRESHOLD,
            "llm_weight": LLM_WEIGHT,
            "stylometric_weight": STYLOMETRIC_WEIGHT,
        },
    }
