"""Signal 1: LLM-based holistic assessment via Groq.

Asks an LLM to estimate whether text reads as AI- or human-generated. Captures
semantic and stylistic coherence in a way the structural signal cannot.

Output: dict with
  - score: float in [0, 1] where 1 means "almost certainly AI"
  - reasoning: short natural-language explanation from the model
  - ok: bool indicating whether the call succeeded
  - model: which Groq model produced the verdict
"""

from __future__ import annotations

import json
import os
import re
from typing import Any

from groq import Groq

_DEFAULT_MODEL = os.environ.get("GROQ_MODEL", "llama-3.1-8b-instant")

_SYSTEM_PROMPT = (
    "You are a careful text-attribution analyst. Given a passage, you assess "
    "the probability that it was generated by an AI language model (as opposed "
    "to written by a human). Consider: stylistic uniformity, hedging language, "
    "list-y structure, generic transitions, lack of personal voice, and "
    "over-polished prose as AI signals. Consider: personal anecdote, irregular "
    "rhythm, idiosyncratic word choice, typos, and lived-in detail as human "
    "signals. You are uncertain by default. Avoid overconfident verdicts on "
    "short or ambiguous passages.\n\n"
    "Reply with ONLY a compact JSON object of the form:\n"
    '{"ai_probability": <float 0-1>, "reasoning": "<one sentence>"}\n'
    "No prose outside the JSON."
)


def _build_client() -> Groq | None:
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key or api_key == "your-groq-api-key-here":
        return None
    return Groq(api_key=api_key)


def _parse_response(raw: str) -> tuple[float, str]:
    """Pull ai_probability and reasoning out of the model's reply.

    Models occasionally wrap JSON in code fences or add a stray sentence; the
    regex finds the first {...} block to make parsing resilient.
    """
    match = re.search(r"\{.*\}", raw, flags=re.DOTALL)
    if not match:
        raise ValueError(f"no JSON object in model reply: {raw!r}")
    payload: dict[str, Any] = json.loads(match.group(0))
    score = float(payload["ai_probability"])
    if not 0.0 <= score <= 1.0:
        raise ValueError(f"ai_probability out of range: {score}")
    reasoning = str(payload.get("reasoning", "")).strip()
    return score, reasoning


def score_with_llm(text: str, model: str | None = None) -> dict[str, Any]:
    """Return the LLM signal's verdict on a passage.

    If the API key is missing or the call fails, returns a neutral 0.5 with
    ok=False so the rest of the pipeline can degrade gracefully rather than
    crash. Callers should weight ok=False signals less in scoring.
    """
    chosen_model = model or _DEFAULT_MODEL
    client = _build_client()
    if client is None:
        return {
            "score": 0.5,
            "reasoning": "GROQ_API_KEY not configured; LLM signal unavailable.",
            "ok": False,
            "model": chosen_model,
        }

    try:
        completion = client.chat.completions.create(
            model=chosen_model,
            temperature=0.0,
            max_tokens=200,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": f"Passage:\n\n{text}"},
            ],
        )
        raw = completion.choices[0].message.content or ""
        score, reasoning = _parse_response(raw)
    except Exception as exc:  # noqa: BLE001 — degrade rather than crash the pipeline
        return {
            "score": 0.5,
            "reasoning": f"LLM signal errored: {type(exc).__name__}: {exc}",
            "ok": False,
            "model": chosen_model,
        }

    return {
        "score": score,
        "reasoning": reasoning,
        "ok": True,
        "model": chosen_model,
    }
